import assert from 'node:assert/strict';
import { spawn, execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, join } from 'node:path';
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
const php = process.env.PHP_BINARY || (process.platform === 'win32' ? join(process.env.USERPROFILE,'.config/herd/bin/php84/php.exe') : 'php');
const chromePath = process.env.CHROME_BINARY || 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const password = readFileSync('.local/admin-credentials.txt','utf8').match(/Password: (.+)/)[1];
execFileSync(php,['scripts/test-setup.php']);
mkdirSync('.local/screenshots',{recursive:true});
const chrome = spawn(chromePath, ['--headless=new','--disable-gpu','--remote-debugging-address=127.0.0.1','--remote-debugging-port=9223',`--user-data-dir=${resolve('.local/chrome-tests')}`,'--no-first-run','--no-default-browser-check','--disable-background-networking','about:blank'],{stdio:'ignore',windowsHide:true});
let passed=0; let failed=0; let socket;
async function check(label, fn) { try { await fn(); passed++; console.log(`PASS ${label}`); } catch(error) { failed++; console.error(`FAIL ${label}: ${error.message}`); } }
try {
  let target;
  for (let i=0;i<50;i++) {
    try { target=await (await fetch('http://127.0.0.1:9223/json/new?about:blank',{method:'PUT'})).json(); break; } catch { await sleep(200); }
  }
  if(!target) throw new Error('Chrome debugging endpoint did not start');
  socket=new WebSocket(target.webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{ socket.addEventListener('open',resolve,{once:true}); socket.addEventListener('error',reject,{once:true}); });
  const pending=new Map(); let id=0; const exceptions=[];
  socket.addEventListener('message',({data})=>{ const message=JSON.parse(data); if(message.id) { const operation=pending.get(message.id); pending.delete(message.id); message.error ? operation.reject(new Error(message.error.message)) : operation.resolve(message.result); } else if(message.method==='Runtime.exceptionThrown') exceptions.push(message.params.exceptionDetails.text); });
  const send=(method,params={})=>new Promise((resolve,reject)=>{const request=++id;pending.set(request,{resolve,reject});socket.send(JSON.stringify({id:request,method,params}));});
  const evaluate=async(expression)=>{const result=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(result.exceptionDetails) throw new Error(result.exceptionDetails.exception?.description || result.exceptionDetails.text);return result.result.value;};
  const navigate=async(path)=>{await send('Page.navigate',{url:`http://127.0.0.1:5174${path}`});await sleep(1000);};
  const viewport=async(width)=>{await send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<768});await sleep(100);};
  const fill=async(selector,values)=>evaluate(`(()=>{const form=document.querySelector(${JSON.stringify(selector)});const values=${JSON.stringify(values)};for(const [key,value] of Object.entries(values)){const input=form.elements.namedItem(key);if(input instanceof RadioNodeList) input.value=value;else input.value=value;}return true;})()`);
  const submit=async(selector)=>{await evaluate(`document.querySelector(${JSON.stringify(selector)}).requestSubmit()`);await sleep(700);};
  await send('Page.enable');await send('Runtime.enable');
  await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
  await navigate('/');
  for(const width of [320,375,390,430,768,1024,1280,1440]) await check(`public page has no overflow at ${width}px`,async()=>{await viewport(width);assert.ok(await evaluate('document.documentElement.scrollWidth <= innerWidth + 1'));});
  await check('approved review empty state contains no fake testimonial',async()=>assert.ok(await evaluate('document.querySelector("[data-reviews]").textContent.includes("EVERY COLLABORATION")')));
  await check('mobile menu opens and anchor closes it',async()=>{await viewport(390);await evaluate('document.querySelector(".menu-toggle").click()');assert.equal(await evaluate('document.querySelector(".menu-toggle").getAttribute("aria-expanded")'),'true');await evaluate('document.querySelector(".mobile-menu a").click()');assert.equal(await evaluate('document.querySelector(".menu-toggle").getAttribute("aria-expanded")'),'false');});
  await check('contact dialog opens, closes, and restores focus',async()=>{await evaluate('document.querySelector(".hero-actions .js-contact").focus();document.querySelector(".hero-actions .js-contact").click()');assert.ok(await evaluate('document.querySelector(".contact-panel").open'));await evaluate('document.querySelector(".panel-close").click()');assert.ok(await evaluate('!document.querySelector(".contact-panel").open && document.activeElement.matches(".hero-actions .js-contact")'));});
  await check('feature film retains premium playback without native controls',async()=>{assert.equal(await evaluate('document.querySelector("[data-feature-video] video").controls'),false);await evaluate('document.querySelector(".film-play").click()');await sleep(1200);assert.ok(await evaluate('document.querySelector("[data-feature-video]").classList.contains("is-playing")'));await evaluate('document.querySelector("[data-feature-video] video").pause()');});
  await check('portfolio, SEO, footer, and social links remain present',async()=>assert.ok(await evaluate('!!document.querySelector("#work .project-media") && !!document.querySelector("link[rel=canonical]") && !!document.querySelector(".footer") && document.querySelector(".js-discord").href.includes("nRRkhPwBA") && document.querySelector(".js-email").href.includes("Acerbox27")')));
  await check('native review validation rejects empty form',async()=>assert.equal(await evaluate('document.querySelector("[data-review-form]").checkValidity()'),false));
  await check('star input supports keyboard selection',async()=>{await evaluate('document.querySelector("input[name=rating][value=\\"4\\"]").focus()');await send('Input.dispatchKeyEvent',{type:'keyDown',key:' ',code:'Space',windowsVirtualKeyCode:32});await send('Input.dispatchKeyEvent',{type:'keyUp',key:' ',code:'Space',windowsVirtualKeyCode:32});assert.equal(await evaluate('document.querySelector("[data-review-form]").elements.rating.value'),'4');});
  await check('visitor submits review and sees awaiting-approval message',async()=>{await fill('[data-review-form]',{client_name:'Browser Test Client',rating:'5',review_text:'<script>globalThis.xss=true</script> Development browser test review. Not a real testimonial.'});await submit('[data-review-form]');assert.ok(await evaluate('document.querySelector("[data-review-form] [data-feedback]").textContent.includes("awaiting approval")'));});
  await check('pending browser review stays hidden publicly',async()=>assert.ok(!(await evaluate('document.querySelector("[data-reviews]").textContent')).includes('Browser Test Client')));
  await check('shoot-day selection explains longer windows and resets date/time',async()=>{await evaluate('document.querySelector("#booking-type").value="shoot";document.querySelector("#booking-type").dispatchEvent(new Event("change"))');assert.ok(await evaluate('document.querySelector("[data-booking-description]").textContent.includes("dedicated shoot window")'));await evaluate('document.querySelector("#booking-type").value="consultation";document.querySelector("#booking-type").dispatchEvent(new Event("change"))');});
  await check('booking email has accessible native validity checking',async()=>{await evaluate('document.querySelector("#booking-email").value="invalid"');assert.equal(await evaluate('document.querySelector("#booking-email").checkValidity()'),false);});
  await check('availability network failure is visible and retry restores the calendar',async()=>{await send('Network.enable');await send('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:-1,uploadThroughput:-1});await evaluate('document.querySelector("[data-refresh-availability]").click()');await sleep(300);assert.ok(await evaluate('document.querySelector("[data-calendar-status]").textContent.includes("Check your connection")'));await send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});await evaluate('document.querySelector("[data-refresh-availability]").click()');await sleep(500);assert.ok(await evaluate('!!document.querySelector(".date-available")'));});
  await check('booking prepares mailto without saving or reserving a request',async()=>{
    await evaluate('globalThis.mailtoDraft="";globalThis.bookingPosts=0;const originalClick=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){if(this.href.startsWith("mailto:")){globalThis.mailtoDraft=this.href;return;}return originalClick.call(this);};const originalFetch=window.fetch;window.fetch=function(...args){if(String(args[0]).includes("route=bookings"))globalThis.bookingPosts++;return originalFetch.apply(this,args);};document.querySelector(".date-available").click()');
    await fill('[data-booking-form]',{name:'Browser Email Client',email:'browser@example.invalid',phone:'',notes:'Development browser email request',slot:await evaluate('document.querySelector("#booking-time").options[1].value')});
    await submit('[data-booking-form]');
    const href=await evaluate('globalThis.mailtoDraft');assert.ok(href.startsWith('mailto:Acerbox27@gmail.com?'));assert.ok(decodeURIComponent(href).includes('Browser Email Client'));assert.ok(decodeURIComponent(href).includes('America/New_York'));
    assert.equal(await evaluate('globalThis.bookingPosts'),0);assert.equal(execFileSync(php,['tests/db-tools.php','counts'],{encoding:'utf8'}).trim(),'0,0');
    assert.ok(await evaluate('document.querySelector("[data-booking-form] [data-feedback]").textContent.includes("Nothing has been sent or reserved")'));
    assert.ok(await evaluate('!document.querySelector("[data-email-draft]").hidden && document.querySelector("#booking-name").value==="Browser Email Client"'));
  });
  await check('long email draft is preserved for copying instead of truncating',async()=>{await fill('[data-booking-form]',{notes:'Long project details '.repeat(80)});await submit('[data-booking-form]');assert.ok(await evaluate('document.querySelector("[data-booking-form] [data-feedback]").textContent.includes("Copy the details")'));assert.ok(await evaluate('!document.querySelector("[data-email-link]").href.includes("&body=") && document.querySelector("[data-email-text]").value.includes("Long project details ".repeat(80).trim())'));});
  await check('copy fallback selects the draft when clipboard permission is unavailable',async()=>{await evaluate('Object.defineProperty(navigator,"clipboard",{configurable:true,value:{writeText:()=>Promise.reject(new Error("Unavailable"))}});document.querySelector("[data-copy-email]").click()');await sleep(200);assert.ok(await evaluate('document.querySelector("[data-booking-form] [data-feedback]").textContent.includes("Select and copy") && document.querySelector("[data-email-text]").selectionEnd>0'));});
  await evaluate('document.querySelector("#booking").scrollIntoView()');await sleep(200);
  await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false}).then(({data})=>writeFileSync('.local/screenshots/public-mobile.png',Buffer.from(data,'base64')));
  await navigate('/admin.html');
  await check('Jake-only sign-in uses the secure backend',async()=>{await fill('[data-login-form]',{username:'jake',password});await submit('[data-login-form]');assert.ok(await evaluate('!document.querySelector("[data-admin-content]").hidden'));});
  for(const width of [320,375,390,430,768,1024,1280,1440]) await check(`management page has no overflow at ${width}px`,async()=>{await viewport(width);assert.ok(await evaluate('document.documentElement.scrollWidth <= innerWidth+1'));});
  await check('Jake approves a pending review through the UI',async()=>{await evaluate('Array.from(document.querySelectorAll("[data-admin-reviews] .admin-record")).find(record=>record.textContent.includes("Browser Test Client")).querySelector("button").click()');await sleep(700);assert.ok(!(await evaluate('document.querySelector("[data-admin-reviews]").textContent')).includes('Browser Test Client'));});
  await check('dashboard contains only review moderation, no booking or availability controls',async()=>assert.ok(await evaluate('!!document.querySelector("[data-admin-reviews]") && !document.querySelector("#admin-bookings, #admin-availability, [data-slot-form], [data-block-form], [data-block-window-form], [data-admin-bookings]")')));
  await check('approved reviews render as text without executing markup',async()=>{await navigate('/');assert.ok(await evaluate('document.querySelector("[data-reviews]").textContent.includes("Browser Test Client")'));assert.ok(await evaluate('!document.querySelector("[data-reviews] script") && !globalThis.xss'));});
  await check('Jake can delete a review using the management UI',async()=>{await navigate('/admin.html');await evaluate('document.querySelector("[data-review-filter]").value="approved";document.querySelector("[data-review-filter]").dispatchEvent(new Event("change"));window.confirm=()=>true;document.querySelector("[data-admin-reviews] .admin-record .admin-actions button:last-child").click()');await sleep(700);assert.ok(await evaluate('document.querySelector("[data-admin-reviews]").textContent.includes("No approved reviews")'));});
  await check('management sign-out clears private content and requires sign-in',async()=>{await evaluate('document.querySelector("[data-logout]").click()');await sleep(700);assert.ok(await evaluate('document.querySelector("[data-admin-content]").hidden && !document.querySelector("[data-login-form]").hidden && document.querySelector("[data-admin-reviews]").children.length===0'));});
  await check('normal-motion entrance remains functional',async()=>{await send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});await navigate('/');await sleep(3500);assert.ok(await evaluate('!document.querySelector(".page-loader") && Number(getComputedStyle(document.querySelector(".reveal-item")).opacity)>0.9'));});
  await viewport(1440);await evaluate('const rect=document.querySelector(".booking-layout").getBoundingClientRect();window.scrollTo({top:rect.top+scrollY-100,behavior:"instant"})');await sleep(1200);
  const formRect=await evaluate('(()=>{const rect=document.querySelector(".booking-layout").getBoundingClientRect();return {x:rect.x+scrollX,y:rect.y+scrollY,width:rect.width,height:rect.height,scale:1};})()');
  await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:formRect}).then(({data})=>writeFileSync('.local/screenshots/booking-desktop.png',Buffer.from(data,'base64')));
  await check('no uncaught browser exceptions',async()=>assert.deepEqual(exceptions,[]));
} catch(error) { failed++;console.error(error.stack); }
finally { socket?.close();chrome.kill();console.log(`Browser checks: ${passed} passed, ${failed} failed`);if(failed)process.exitCode=1; }
